# Generated by Django 4.2.7 on 2023-11-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_storetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTransaction',
            fields=[
                ('transaction_id', models.CharField(default=0, max_length=200, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salesperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.storesalesperson')),
            ],
            options={
                'db_table': 'store_transactions',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.storetransaction'),
        ),
    ]
