# Generated by Django 4.2.7 on 2023-11-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_storetransaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Company_income',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='business_category',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='income',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='marriage_status',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storetransaction',
            name='transaction_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='storewarehouse',
            table='store_warehouse',
        ),
    ]
